Convert CLI to cobra framework
redhat-cop/dash pull request #30
Opened 2019-11-08 17:29 UTC by etsauer

resolves #29

2019-11-09 21:04 UTC, sabre1041 requested changes
@etsauer Left a comment on the `version` subcommand

2019-11-09 21:04 UTC, sabre1041 commented on cmd/version.go
> +	Short: "Print the version number of Hugo",
@etsauer boilerplate code?

2019-11-20 19:44 UTC, pabrahamsson commented
@etsauer I have some work ready for #33 but it is based on this PR so it should be merged first. No rush just wanted to check in and see where you are with this PR?

2023-11-20 14:47 UTC, garethahealy commented
archiving

2023-11-20 14:47 UTC, closed without merging